name: NodeJS with Webpack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set-up Node
      uses: actions/setup-node@v1
      with:
        node-version: "16.x"
    - run: npm install
    - run: npm run build
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: gh-pages
        build_dir: build
